name: 'Smack Integration Tests'
description: 'Run Tests'
inputs:
  ipAddress:
    description: 'The IP address of the server under test'
    required: true
    default: '127.0.0.1'
  domain:
    description: 'XMPP domain name of server under test'
    required: true
    default: 'example.org'
  timeout:
    description: 'Amount of milliseconds after which a XMPP action (typically an IQ request) is considered timed out.'
    required: false
    default: '60000'
  adminAccountUsername:
    description: 'Account name of a pre-existing user that is allowed to create other users, per XEP-0133. If not provided, In-band registration (XEP-0077) will be used.'
    required: false
  adminAccountPassword:
    description: 'Password for the admin account.'
    required: false
  smackVersion:
    description: 'Version of the Smack library providing the SINT test implementation.'
    required: true
    default: '4.4.6'
  disabledTests:
    description: 'Comma-separated list of of tests that are to be skipped (eg: "EntityCapsTest,SoftwareInfoIntegrationTest")'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.3

    - run: |
        sudo echo "${{ inputs.ipAddress }} ${{ inputs.domain }}" | sudo tee -a /etc/hosts
        gradle --console=plain \
               --build-file ${{ github.action_path }}/test.gradle \
               -PsmackVersion="${{ inputs.smackVersion }}" \
               -q dependencies
        gradle \
          --console=plain \
          --stacktrace \
          run \
          -b ${{ github.action_path }}/test.gradle \
          -PsmackVersion="${{ inputs.smackVersion }}" \
          -Dsinttest.service="${{ inputs.domain }}" \
          -Dsinttest.securityMode=disabled \
          -Dsinttest.replyTimeout=${{ inputs.timeout }} \
          -Dsinttest.adminAccountUsername="${{ inputs.adminAccountUsername }}" \
          -Dsinttest.adminAccountPassword="${{ inputs.adminAccountPassword }}" \
          -Dsinttest.enabledConnections=tcp \
          -Dsinttest.dnsResolver=javax \
          -Dsinttest.disabledTests="-Dsinttest.disabledTests=${{ inputs.disabledTests }}"
      shell: bash
