name: 'Smack Integration Tests'
description: 'Run Tests'
inputs:
  domain:
    description: 'XMPP domain name of server under test'
    required: true
    default: 'example.org'
  timeout:
    description: 'Amount of milliseconds after which a XMPP action (typically an IQ request) is considered timed out.'
    required: false
    default: 60000
  adminAccountUsername:
    description: 'Account name of a pre-existing user that is allowed to create other users (using ad-hoc commands).'
    required: false
  adminAccountPassword:
    description: 'Password for the admin account.'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.3

    - run: executeTests.sh -d -l -h ${{ inputs.domain }} -u ${{ inputs.adminAccountUsername }} -p ${{ inputs.adminAccountPassword }}
      working-directory: ${{ github.action_path }}
      shell: bash
